name: oklahoma_tax_credit_insights
version: '1.0'
config-version: 2

# which profile to use from ~/.dbt/profiles.yml
profile: dev

# where your models live, relative to repo root:
model-paths: ["models"]

# compiled artifacts go here:
target-path: "target"

# clean <repo>/target & dbt_packages on `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"
