version: 2

sources:
  - name: willthompson
    database: WILLTHOMPSON
    schema: PUBLIC
    tables:
      - name: tax_credits_2023
        identifier: TAX_CREDITS_2023  # Changed from RAW_TAX_CREDITS to TAX_CREDITS_2023
        description: "Raw Oklahoma tax credits data"