version: 2

sources:
  - name: willthompson
    database: WILLTHOMPSON
    schema: PUBLIC
    tables:
      - name: raw_tax_credits
        identifier: RAW_TAX_CREDITS  # Update this to match your actual raw table name
        description: "Raw Oklahoma tax credits data"