version: 2

models:
  - name: stg_tax_credits
    description: "Staging model for tax credit data"
    columns:
      - name: fiscal_year
        description: "Fiscal year of the credit"
        tests:
          - not_null
      - name: tax_year
        description: "Tax year the credit was filed"
        tests:
          - not_null
      - name: recipient_name
        description: "Name of the recipient or business"
        tests:
          - not_null
      - name: credit_type
        description: "Type/category of the credit"
        tests:
          - not_null
      - name: amount
        description: "Amount of credit claimed"
        tests:
          - not_null
      - name: credit_description
        description: "Details or notes about the credit"

  - name: mart_credit_summary
    description: "Summarized credit claims by year and type"
    columns:
      - name: credit_type
        description: "Category of credit"
        tests:
          - not_null
      - name: fiscal_year
        description: "Year of the credit"
        tests:
          - not_null
      - name: total_claimed
        description: "Sum of credits claimed for that type and year"
        tests:
          - not_null

  - name: mart_top_recipients
    description: "Top 10 recipients with the highest total tax credit claims"
    columns:
      - name: recipient_name
        description: "Name of the recipient or business"
        tests:
          - not_null
      - name: total_claimed
        description: "Total amount of credits claimed"
        tests:
          - not_null
